### ISSUE TITLE
Please rebuild the package against latest fcitx5 flatpak version

### ISSUE THREAD

**Issue by wengxt** [flathub/org.fcitx.Fcitx5.Addon.McBopomofo#3]
It's not due to ABI change to fcitx itself, but it's upgrading the runtime to 22.08, all addon package need to be adjusted accordingly.

See
https://github.com/flathub/org.fcitx.Fcitx5/pull/17/files#diff-9c4514a5cfdc42b8838d749e15085d92a39a43ef8058cb60cbf6385d7834e7ad

**Comment by lukhnos** [comment]
Done. Thanks for the heads-up!
